### ISSUE TITLE
Não permitir a criação de planos de comissão com valores negativos

### ISSUE THREAD

**Issue by YouFool** [codenation-dev/squad-2-ad-python-2#1]
### Problema a ser resolvido

Conforme desenvolvido na #12 é possível realizar o cadastro de planos de comissões via API e via formulário HTML. 

Porém, ambos meios de cadastro permitem valores negativos, exemplo de planos cadastrados:
`[{"id_plano":2,"descricao":"aa","valor_minimo":"-1.00","percent_min":"-1.10","percent_max":"-1.20"},{"id_plano":1,"descricao":"abc","valor_minimo":"-1.00","percent_min":"-2.00","percent_max":"-3.00"}]`

### Análise
- Deverão ser feitas validações para que não seja permitido cadastrar um plano com valores negativos. Talvez possamos realizar essa validação na própria (entidade)[https://stackoverflow.com/questions/12384460/allow-only-positive-decimal-numbers]
- Também deve ser validado se % mínimo não é maior que % máximo.

### Critérios de aceite
- API Retorna erro 400 (BAD REQUEST) ao tentar criar um plano com valores negativos
- Camada de visão retorna erro ao ao tentar criar um plano com valores negativos (seria interessante que os campos HTML retornassem um feedback visual ao usuário)
- 2 em % mínimo e 1 em % mínimo não deve ser possível

Exemplo: https://www.ctrl.blog/media/hero/html-input-number-decimal-person-height.544x306.jpeg

**Comment by jmiguelh** [comment]
Merged #3 into dev.
