### ISSUE TITLE
Criar estrutura para apresentação

### ISSUE THREAD

**Issue by YouFool** [codenation-dev/squad-2-ad-python-2#11]
Devemos criar um ppt com os slides para realizar a apresentação

Verificar se é necessário uma documentação de entrega do projeto, caso sim, deverá ser adicionado nos slides.

**Comment by guilhermelemke** [comment]
Estrutura da apresentação criada, faltam alguns dados que só poderão ser acrescentados ao final do desenvolvimento. Se tiverem alguma sugestão, ou algo que foi deixado de fora, podemos incluir ainda.
[Apresentação Projeto Final Codenation.pdf](https://github.com/codenation-dev/squad-2-ad-python-2/files/3437298/Apresentacao.Projeto.Final.Codenation.pdf)

**Comment by YouFool** [comment]
Apresentação com algumas alterações:

[Apresentação Projeto Final Codenation (1).pptx](https://github.com/codenation-dev/squad-2-ad-python-2/files/3449342/Apresentacao.Projeto.Final.Codenation.1.pptx)

**Comment by YouFool** [comment]
Estrutura está ok com algumas pequenas alterações.
Qualquer nova adição, reabrir a issue e inserir a nova versão do arquivo

**Comment by YouFool** [comment]
Respostas para algumas perguntas que devem ser respondidas na apresentação 😄 
# Apresentação final

---

- Breve apresentação

    > “Oi pessoal, eu me chamo **NOME** e vou apresentar para vocês o projeto final que fiz com a squad 2 - SECOMA da Aceleração Python da Codenation.”

- Descrição do projeto e desenvolvimento do processo que a squad utilizou para resolver o problema
    - O projeto trata-se de um software de gestão de comissão, e tem o objetivo de ajudar os usuários desse sistema com a gestão de custos relativos à comissões de venda, seja ele um vendedor ou um gestor de vendas.
- Divisão de tarefas entre os membros da squad e quais foram suas principais responsabilidades
    - As tarefas foram criadas no backlog do produto, onde cada membro do time assumia responsabilidade pela issue que se sentia confortável em atuar
    - Todos, diretamente e indiretamente, ficaram responsáveis por fazer uma pequena parte de tudo
    - Um PR não poderia ser aprovado pelo próprio criador
- Tecnologias utilizadas e eficácia
    - Django e DRF: **Rapidez e facilidade** em criar APIs sem *boiler-plate* code
    - SQLite: Banco de dados "standalone", com zero necessidade de configuração com o Django
    - Git & GitHub: Versionamento de código distribuído, gerenciamento do produto
    - RAML: Documentação da API de maneira simples
    - Heroku: Serviço usado para fazer o CI/CD da nossa aplicação
- Aprendizados destacados durante o processo e ao final do projeto
    - Dentro de um time existem pessoas com **conhecimentos** diferentes em **níveis** diferentes. Embora no começo isso pareça algo negativo para os mais experientes, todo o time sai ganhando ao entregar um produto com conhecimentos diversificados.
    - Quanto mais comunicação entre os integrantes, mais rápido ocorre o desenvolvimento
- Duas principais dificuldades, e como foram contornadas
    - A "perda" de um integrante da equipe: foco na entrega e distribuição da carga conforme as capacidades de cada indivíduo
    - Tempo: todos do time tinham uma rotina cheia. Foi muito dificultoso nos organizarmos para conversar e/ou resolver as issues. Uma das soluções adotadas foi realizar calls individuais e repassar o que foi discutido integrante-por-integrante
- Dois principais acertos ou escolhas acertadas que fizeram diferença no projeto e por quê.
    - Banco de dados SQLite: por ser executado junto com a aplicação e ser um standalone, não foi necessário configurar um banco de dados para a aplicação funcionar
    - Merge de PR após validação de 1 ou mais integrantes do time: descoberta de pequenos erros antes de serem encontrados, melhoria na qualidade do código em geral e compartilhamento de conhecimento entre os integrantes.

**Comment by guilhermelemke** [comment]
Pessoal incluí o grupo no primeiro slide para apresentação.
Boa sorte a todos :)

[Apresentacao.Projeto.Final.Codenation.1.pptx](https://github.com/codenation-dev/squad-2-ad-python-2/files/3453756/Apresentacao.Projeto.Final.Codenation.1.pptx)
